### PR TITLE
#2 router and routes

### PR DESCRIPTION
**Pull request by JarodXP**

### CODE REVIEW

**Comment by JarodXP** [comment]
Hi @Tutt-J , please review this first request. Thanks

**Comment by Tutt-J** [comment]
Hi @JarodXP,

Please explain me :

- Why use "require __DIR__" on controller. I want you to use twig render.
- Please add comments on application.php, Route.php (and explain why use $requestedUri), Router.php
- What's the point of using "header('location:/admin/posts');" on homeAction, I think it must be a better idea to directly use route.yml to use the good controller.

**Comment by JarodXP** [comment]
@Tutt-J 
Tks,

>  -     Why use "require DIR" on controller. I want you to use twig render:

_Because I wanted to have only the Rouing system on this first PR.
I'm implmenting Twig on the next one._

> -     Please add comments on application.php, Route.php (and explain why use $requestedUri), Router.php
_Comments added,
RequestedUri removed_

> -     What's the point of using "header('location:/admin/posts');" on homeAction, I think it must be a better idea to directly use route.yml to use the good controller.

_Ok, done_

**Comment by Tutt-J** [comment]
I thing it's a better idea to user twig directly. Like this, you have a first merge with route ==> Controller ==> View clean

**Comment by Tutt-J** [comment]
And when you comment your php file please explain where et how you use methods...

**Pull request closed without merging**
